# Generated by Django 2.2.5 on 2019-09-08 11:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='maximum_number_of_tickets',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='event',
            name='tickets',
            field=models.ManyToManyField(blank=True, null=True, related_name='tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
