# Generated by Django 2.2.5 on 2019-09-08 11:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190908_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tickets',
            field=models.ManyToManyField(blank=True, related_name='tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
