# Generated by Django 2.2.5 on 2019-09-09 00:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20190908_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookticket',
            name='purchase_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='occurance',
            field=models.DateTimeField(),
        ),
    ]
