# Generated by Django 2.2.5 on 2019-09-09 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20190909_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookticket',
            name='purchase_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
